#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\EventDispatcher\EventDispatcher;

$dispatcher = new EventDispatcher();
$dispatcher->addListener(\dio\Events\BlacklistUpdated::class, [new \dio\EventListeners\SendEmailToPublisher(), 'onEvent']);

(new \dio\Jobs\OptimizationJob($dispatcher))->run();
